### ISSUE TITLE
Icon names incorrect / sliced in two

### ISSUE THREAD

**Issue by brianguertin** [Defkil/material-design-icons-literal-types#1]
Sometimes the icon names seem to be generated incorrectly, for example in Material Symbols I see:

```ts
| 'left_pane'
| 'l_open'
```

When it should be
```ts
| 'left_panel_open'
```

P.S. this is a great package to have, thank you :pray:

**Comment by Defkil** [comment]
Hey, thanks for bringing this up! I've solved the icon name generation problem by tweaking the function. Glad you're finding the package useful.
I've also created a new issue #2 to implement a line comparison feature. I'll be working on that in the coming days to ensure this kind of problem doesn't happen again.
